name: Workflow for update data

on:
  push:
  schedule:
      - cron: '30 0 * * 5'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        with: 
          token: ${{ secrets.PAT }}
          persist-credentials: true
        uses: actions/checkout@v2
      - name: Update adzans
        uses: ./.github/action-update-data/
      - name: Commit changes
        uses: EndBug/add-and-commit@v7.0.0
        with:
          message: "Update Data"
          author_name: github-actions
          author_email: 41898282+github-actions[bot]@users.noreply.github.com
          push: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
      - uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PAT }}
          branch: ${{ github.ref }}
